### ISSUE TITLE
Null exception from ImageClassification component

### ISSUE THREAD

**Issue by zaynelt** [muenzpraeger/salesforce-einstein-platform-apex#39] opened 2017-12-04 19:21 UTC
If a user tries to interact with the Prediction subtab & models picklist before uploading a file image, the component throws an unhandled null exception.

Issue: 
[https://github.com/muenzpraeger/salesforce-einstein-platform-apex/blob/master/force-app/main/default/aura/EinsteinImageClassification/EinsteinImageClassificationController.js](url)
Begins on Line 4:
`if (files && files.length > 0)`

See fix (controller.js markup changes):
[https://github.com/muenzpraeger/salesforce-einstein-platform-apex/commit/429298f8b34b52c733e95b02b491e1c06f375664#diff-83f5f29d4ef7e13f350f2c78b816dbb6](url)

**Comment by muenzpraeger** [comment] 2017-12-05 13:41
Can you please specify the steps to reproduce this? Thanks!

**Comment by zaynelt** [comment] 2017-12-05 17:10
Click on 'Image Classification'. Click on 'Prediction'. Click on 'Models' picklist. Select any value.

**Comment by muenzpraeger** [comment] 2017-12-06 11:17
Cannot reproduce. I guess it's meanwhile fixed by something else. ;-)

**Closed by muenzpraeger** 2017-12-06 11:17 UTC
